### ISSUE TITLE
JSDoc Instead of JSON

### ISSUE THREAD

**Issue by shadowtime2000** [Pika1998/express-autodocs#4] opened 2020-09-26 06:28 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implement a parser that allows you to use JSDoc-like syntax instead of having to type json in comments.

**Describe alternatives you've considered**
None

**Comment by Pika1998** [comment] 2020-09-26 06:30
This is a good idea, we can go ahead with this 😁

**Comment by rahil1304** [comment] 2020-10-03 14:56
Hey
I'd like to work on this issue. Could you please provide some more details if possible, so I can better understand what exactly is required. @Pika1998

**Comment by Pika1998** [comment] 2020-10-03 15:03
Sure @rahil1304 , you can work on this

**Current Working**

Right now to provide a description to the API like (label, description, inputs, outputs) we are using a multiline comment above the API where we pass JSON

**Example**
```js
/*  
{
    "description":"Checks for token and gets the logged in user",
    "inputs":{
        "x-auth-token":"The JWT Token in header"
    },
    "label":"Public",
    "outputs":{
        "user":"The user object stored in database",
    }
}
*/
router.get("/user", auth, (req, res) => {
  User.findById(req.user.id)
    .select("-password")
    .then((user) => {
      res.json(user);
    });
});
```

Here the problem is, the user has to follow the JSON syntax strictly, because what our code is doing is ```js JSON.parse(textInComment)``` 

So here are a few problems with this
1. The action won't be able to parse if the JSON syntax is not followed by users
2. There is a need to improve this because JSON is somewhat difficult to write 

**Proposed Alternative**

We can implement a parser like [JSDoc](https://jsdoc.app/about-getting-started.html) which is used to provide code definitions for a cleaner code

Their syntax is somewhat like this
```js
/**
 * Represents a book.
 * @constructor
 * @param {string} title - The title of the book.
 * @param {string} author - The author of the book.
 */
function Book(title, author) {
}
```

Just that instead of functions we have to apply this for our API definition (which does not change anything in the code except how we parse the data)

**Comment by rahil1304** [comment] 2020-10-03 15:16
Okay thanks I'll look into it. Which file currently implements the json parser to add description? @Pika1998

**Comment by Pika1998** [comment] 2020-10-03 15:21
https://github.com/Pika1998/express-autodocs/blob/master/helpers/demestifyAPI.js

Here the following method gets the job done
```js
function getCommentedParams(index, file) {
  let startIndex = index - 3; //  will be the character before '*' character
  let currentIndex = startIndex;
  let params = '';
  while (file.charAt(currentIndex) != '*') {
    params = params + file.charAt(currentIndex);
    currentIndex -= 1;
  }
  try {
    params = JSON.parse([...params].reverse().join('').trim());
    return params;
  } catch (err) {
    console.log(
      '\x1b[1m',
      '\x1b[31m',
      `❌ Make sure the params passed in comments are in proper JSON Format.`,
      '\x1b[0m'
    );
    return null;
  }
}

```

This method gets the start Index from where the required comment starts
and it checks for the ending * to get the last index of comment

**Comment by rahil1304** [comment] 2020-10-04 06:44
params = JSON.parse([...params].reverse().join('').trim());
Hey, so I didn't understand why exactly are you reversing the params? @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 06:55
Ok that is because the comment is above the API definition , so basically we detect the comment with reference to our API, since it will always be above API we have to back trace it.  (you will also notice we are reducing the index)

Then once we get the entire content of the comment, we will have to reverse it because we were scanning it as a bottom-up approach

**Comment by rahil1304** [comment] 2020-10-04 07:04
Okay, so I'm trying to test `function demestifyAPI(api, index, file, routeprefix = '')` to make sure it is correctly storying the data in params. Could you give me an example of the (api, index, file) parameters to pass so that I know it's being generated correctly? @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 08:02
Ok wait I will get back to you in few minutes

**Comment by Pika1998** [comment] 2020-10-04 08:10
Ok @rahil1304  here are the params to create the test.
**api**
```js
app.post('/users', auth, function (req, res) {
  res.send('User Created');
})
```
**index**
`584`

**file**
```js
const express = require('express');
const mongoose = require('mongoose');
const path = require('path');
const config = require('config');
var queries = require('./routes/api/queries');
const app = express();
// Body Parser Middleware
app.use(express.json());

/*
    {
      "description":"Creates a new user",
      "label":"Private",
      "inputs":{
        "name":"The username by which he/she logs in",
        "password": "A string password"
      },
      "outputs":{
        "userid":"The id of the new user created",
        "error":"Error message if any"
      }
    }
  */
app.post('/users', auth, function (req, res) {
  res.send('User Created');
});

// Server Connection
const port = process.env.PORT || 5000;
app.listen(port, () => console.log(`Server Started on port ${port}`));

let handleDelete = (req, res) => res.send('Deleted');

```

**Comment by Pika1998** [comment] 2020-10-04 08:10
Also, I feel we should write this as a custom test

**Comment by rahil1304** [comment] 2020-10-04 10:22
> Also, I feel we should write this as a custom test

Sure I can add this once I'm done with the JSDoc task.

**Comment by rahil1304** [comment] 2020-10-04 10:23
https://github.com/Pika1998/express-autodocs/pull/15
I have raised a PR for this issue. Do review it and let me know if any changes are required. @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 10:49
@rahil1304 can you give an example of how you have defined the API in jsdoc?

**Comment by rahil1304** [comment] 2020-10-04 10:52
Yeah sure 
So basically 
`​/**​
​ * Represents a book.​
​ * ​@constructor​
​ * ​@param​ {​string​} title - The title of the book.​
​ * ​@param​ {​string​} author - The author of the book.​
​ */`​
Would be converted to an object which would be like 
`{
   title - "The title of the book.​",
   author - "The author of the book.​"
}`

**Comment by Pika1998** [comment] 2020-10-04 10:53
wait let me try this

**Comment by rahil1304** [comment] 2020-10-04 10:55
Let me know if it does not work or if there are any issues @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 10:56
@rahil1304  I tried to console log the data, but the output is showing {} and there is no data in the output
![image](https://user-images.githubusercontent.com/36433104/95013521-6409fa00-065e-11eb-86eb-4eae7800d9b0.png)

Let me know if I am doing something wrong

**Comment by Pika1998** [comment] 2020-10-04 10:59
```js

  /**​
​ * Represents a book.​
​ * ​@constructor​
​ * ​@param​ {​string​} title - The title of the book.​
​ * ​@param {string} author - The author of the book.​
​ */
  app.post('/users', auth, function (req, res) {
    res.send('User Created');
  });
```

**Comment by rahil1304** [comment] 2020-10-04 10:59
> @rahil1304 I tried to console log the data, but the output is showing {} and there is no data in the output
> ![image](https://user-images.githubusercontent.com/36433104/95013521-6409fa00-065e-11eb-86eb-4eae7800d9b0.png)
> 
> Let me know if I am doing something wrong

The comments seem to be in the wrong format. 
It should have a single * 
something like this
```
/**​
​ * Represents a book.​
​ * ​@constructor​
​ * ​@param​ {​string​} title - The title of the book.​
​ * ​@param {string} author - The author of the book.​
​ */
```

**Comment by rahil1304** [comment] 2020-10-04 11:01
Instead your comments in the picture are 
```
/**​
​ * * Represents a book.​
​ * ​* @constructor​
​ * * ​@param​ {​string​} title - The title of the book.​
​ * ​* @param {string} author - The author of the book.​
​ **/
```

**Comment by Pika1998** [comment] 2020-10-04 11:11
I did try both
```
/**​
​ * Represents a book.​
​ * ​@constructor​
​ * ​@param​ {​string​} title - The title of the book.​
​ * ​@param {string} author - The author of the book.​
​ */
```

**Comment by Pika1998** [comment] 2020-10-04 11:12
@rahil1304 check this image
![image](https://user-images.githubusercontent.com/36433104/95013839-8e5cb700-0660-11eb-8c06-79b66dfa4f27.png)

**Comment by Pika1998** [comment] 2020-10-04 11:13
also in json we are giving array for inputs and outputs
like 
```js
 "inputs":{
        "name":"The username by which he/she logs in",
        "password": "A string password"
      },
      "outputs":{
        "userid":"The id of the new user created",
        "error":"Error message if any"
      }
```
Any idea how we can implement this also ?

**Comment by rahil1304** [comment] 2020-10-04 11:18
What exactly are you logging and in which file to check? @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 11:24
i am just logging the data variable in the getCommentedParams function you created just before it is returned to check it's value

**Comment by rahil1304** [comment] 2020-10-04 11:27
Make sure you are passing the correct index.
![image](https://user-images.githubusercontent.com/32304956/95014158-b5b48380-0662-11eb-9a1f-a976a407242e.png)

it's working correctly in mine

**Comment by rahil1304** [comment] 2020-10-04 11:30
![image](https://user-images.githubusercontent.com/32304956/95014231-1fcd2880-0663-11eb-9658-1889495ec41b.png)

**Comment by Pika1998** [comment] 2020-10-04 11:43
The index is getting detected by the action right? so it should take the correct index anyways

**Comment by Pika1998** [comment] 2020-10-04 11:54
**My Input**
```js
const express = require('express');
const mongoose = require('mongoose');
const path = require('path');
const config = require('config');
var queries = require('./routes/api/queries');
const app = express();
// Body Parser Middleware
app.use(express.json());

/**​
​ * Represents a book.​
​ * ​@constructor​
​ * ​@param​ {​string​} title - The title of the book.​
​ * ​@param {string} author - The author of the book.​
​ */
app.get('/sayHello', (req, res) => {
  res.send('Hello');
});

const port = process.env.PORT || 5000;
app.listen(port, () => console.log(`Server Started on port ${port}`));

let handleDelete = (req, res) => res.send('Deleted');
```

**My Output**
```shell
prafulla@pika-ubuntu:~/Projects/express-autodocs$ npm run dev

> express-autodocs@0.0.2-beta.1 dev /home/prafulla/Projects/express-autodocs
> node -r dotenv/config index.js 

  ✨ Initialized Express AutoDocs 
  🔎 Scanning for Base Level APIs... 
{}
  🆗 Scan Complete   -   Base Level APIs Scanned   1   
  🔎 Detecting Routes... 
  🆗 Scan Complete   -   Routes Detected   0   
  🔎 Scanning Routes For API Calls... 
  ✨ Creating Docss ... 
```

**Comment by rahil1304** [comment] 2020-10-04 12:16
Okay wait let me try checking what is the issue.

**Comment by Pika1998** [comment] 2020-10-04 12:18
Please do, is this the expected log ?

**Comment by rahil1304** [comment] 2020-10-04 12:25
Okay so there is an issue with the index. The index is not being passed properly. I logged the index and it's always 4 more than the desired index. If you see the first example, the index printed is 260, but it should actually be 256. 
![image](https://user-images.githubusercontent.com/32304956/95015433-84d84c80-066a-11eb-914c-ff4ed0ecb4ed.png)

**Comment by rahil1304** [comment] 2020-10-04 12:27
Okay I got the issue. I'll raise a PR with the correction. @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 12:38
Ok i will first merge it in the dev branch, then merge everything into master after we are done with this issue :)

**Comment by rahil1304** [comment] 2020-10-04 12:44
> Ok i will first merge it in the dev branch, then merge everything into master after we are done with this issue :)

Yeah sure. Let me know if there are any more problems. @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 12:45
Hey @rahil1304 unfortunately it is still not working in my codebase, same issue
The output of item log and data log
```js
[
  '**\n' +
    ' * Represents a book.\n' +
    ' * @constructor\n' +
    ' * @param {string} title - The title of the book.\n' +
    ' * @param {string} author - The author of the book.\n' +
    ' '
]
{}
```

**Comment by Pika1998** [comment] 2020-10-04 12:47
can you try this as your server.js
```js
const express = require('express');
const mongoose = require('mongoose');
const path = require('path');
const config = require('config');
var queries = require('./routes/api/queries');
const app = express();
// Body Parser Middleware
app.use(express.json());

/**
 * Represents a book.
 * @constructor
 * @param {string} title - The title of the book.
 * @param {string} author - The author of the book.
 */
app.get('/sayHello', (req, res) => {
  res.send('Hello');
});

// Server Connection
const port = process.env.PORT || 5000;
app.listen(port, () => console.log(`Server Started on port ${port}`));

let handleDelete = (req, res) => res.send('Deleted');
``` and check if you are getting the expected output

**Comment by rahil1304** [comment] 2020-10-04 12:47
Can you confirm if your function has this particular line 
`        file.charAt(currentIndex - 1) == '\r'
`

```
function getCustomParams(index, file) {
  // Backtraces for an immediate multi-line comment
  let descriptionFound = 'unknown';
  let currentIndex = index;
  while (descriptionFound == 'unknown') {
    if (currentIndex != 0) {
      if (
        file.charAt(currentIndex - 1) == ' ' ||
        file.charAt(currentIndex - 1) == '\n' ||
        file.charAt(currentIndex - 1) == '\r'
      ) {
        currentIndex -= 1;
      } else if (file.charAt(currentIndex - 1) == '/') {
        descriptionFound = true;
      } else {
        descriptionFound = false;
      }
    }
  }
  if (descriptionFound) {
    return getCommentedParams(currentIndex, file);
  } else {
    // If no description is present then return null;
    return null;
  }
}
```

**Comment by rahil1304** [comment] 2020-10-04 12:49
> ```js
> const express = require('express');
> const mongoose = require('mongoose');
> const path = require('path');
> const config = require('config');
> var queries = require('./routes/api/queries');
> const app = express();
> // Body Parser Middleware
> app.use(express.json());
> 
> /**
>  * Represents a book.
>  * @constructor
>  * @param {string} title - The title of the book.
>  * @param {string} author - The author of the book.
>  */
> app.get('/sayHello', (req, res) => {
>   res.send('Hello');
> });
> 
> // Server Connection
> const port = process.env.PORT || 5000;
> app.listen(port, () => console.log(`Server Started on port ${port}`));
> 
> let handleDelete = (req, res) => res.send('Deleted');
> ```

Yes it is working on mine @Pika1998 
![image](https://user-images.githubusercontent.com/32304956/95016029-15fcf280-066e-11eb-912f-c960cdbc1df2.png)

**Comment by Pika1998** [comment] 2020-10-04 13:11
![image](https://user-images.githubusercontent.com/36433104/95016533-2fec0480-0671-11eb-93ef-ea37272a50b9.png)

@rahil1304  this is my entire function

**Comment by Pika1998** [comment] 2020-10-04 13:14
> > ```js
> > const express = require('express');
> > const mongoose = require('mongoose');
> > const path = require('path');
> > const config = require('config');
> > var queries = require('./routes/api/queries');
> > const app = express();
> > // Body Parser Middleware
> > app.use(express.json());
> > 
> > /**
> >  * Represents a book.
> >  * @constructor
> >  * @param {string} title - The title of the book.
> >  * @param {string} author - The author of the book.
> >  */
> > app.get('/sayHello', (req, res) => {
> >   res.send('Hello');
> > });
> > 
> > // Server Connection
> > const port = process.env.PORT || 5000;
> > app.listen(port, () => console.log(`Server Started on port ${port}`));
> > 
> > let handleDelete = (req, res) => res.send('Deleted');
> > ```
> 
> Yes it is working on mine @Pika1998
> ![image](https://user-images.githubusercontent.com/32304956/95016029-15fcf280-066e-11eb-912f-c960cdbc1df2.png)

woah i am now really unsure why it doesn't work on my machine lol

**Comment by rahil1304** [comment] 2020-10-04 13:15
Can you send me your `getCommentedParams `function as well? @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 13:15
```js
function getCommentedParams(index, file) {
  let startIndex = index - 3; //  will be the character before '*' character
  let currentIndex = startIndex;
  let params = '';
  let data = {};
  while (file.charAt(currentIndex) != '/') {
    params = params + file.charAt(currentIndex);
    currentIndex -= 1;
  }
  try {
    let item = [...params].reverse().join('').split('\r');
    item.forEach(function (param) {
      let temp = param.split('-');
      if (temp.length == 2) {
        temp[0] = temp[0].trim();
        temp[0] = temp[0].substring(temp[0].lastIndexOf(' '));
        data[temp[0].trim()] = String(temp[1].trim());
      }
    });
    console.log(data);
    return data;
  } catch (err) {
    console.log(
      '\x1b[1m',
      '\x1b[31m',
      `❌ Make sure the params passed in comments are in proper JSDoc Format.`,
      '\x1b[0m'
    );
    return null;
  }
}
```

**Comment by rahil1304** [comment] 2020-10-04 13:16
So I logged item and data, it displays correctly on mine. 
![image](https://user-images.githubusercontent.com/32304956/95016643-e18b3580-0671-11eb-9eb3-abd27da322ba.png)

**Comment by Pika1998** [comment] 2020-10-04 13:17
did you pull from master?

**Comment by rahil1304** [comment] 2020-10-04 13:17
> did you pull from master?

Yes

**Comment by rahil1304** [comment] 2020-10-04 13:17
> ```js
> function getCommentedParams(index, file) {
>   let startIndex = index - 3; //  will be the character before '*' character
>   let currentIndex = startIndex;
>   let params = '';
>   let data = {};
>   while (file.charAt(currentIndex) != '/') {
>     params = params + file.charAt(currentIndex);
>     currentIndex -= 1;
>   }
>   try {
>     let item = [...params].reverse().join('').split('\r');
>     item.forEach(function (param) {
>       let temp = param.split('-');
>       if (temp.length == 2) {
>         temp[0] = temp[0].trim();
>         temp[0] = temp[0].substring(temp[0].lastIndexOf(' '));
>         data[temp[0].trim()] = String(temp[1].trim());
>       }
>     });
>     console.log(data);
>     return data;
>   } catch (err) {
>     console.log(
>       '\x1b[1m',
>       '\x1b[31m',
>       `❌ Make sure the params passed in comments are in proper JSDoc Format.`,
>       '\x1b[0m'
>     );
>     return null;
>   }
> }
> ```

So I copy pasted this function on mine. And it works the same. It's displaying correctly.

**Comment by Pika1998** [comment] 2020-10-04 13:18
wait ill just clone the entire project again :cry:

**Comment by rahil1304** [comment] 2020-10-04 13:18
Just try restarting vscode again, it should work I guess.

**Comment by rahil1304** [comment] 2020-10-04 13:19
So your item is getting logged correctly, only the data is not being logged. So put loggers after item, to check if the item is being properly passed. @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 13:22
@rahil1304 I cloned the entire project again and changed the server.js as I had commented above
Still same error
```js
prafulla@pika-ubuntu:~/Projects/express-autodocs$ npm run dev

> express-autodocs@0.0.2-beta.1 dev /home/prafulla/Projects/express-autodocs
> node -r dotenv/config index.js 

  ✨ Initialized Express AutoDocs 
  🔎 Scanning for Base Level APIs... 
[
  '**\n' +
    ' * Represents a book.\n' +
    ' * @constructor\n' +
    ' * @param {string} title - The title of the book.\n' +
    ' * @param {string} author - The author of the book.\n' +
    ' '
]
{}
  🆗 Scan Complete   -   Base Level APIs Scanned   1   
  🔎 Detecting Routes... 
  🆗 Scan Complete   -   Routes Detected   0   
  🔎 Scanning Routes For API Calls... 
  ✨ Creating Docss ... 
```
this is the log of items aswell as data,

Can you try to clone the project again from master branch and check ? :(

**Comment by Pika1998** [comment] 2020-10-04 13:24
@rahil1304  my code is not running items.forEach and I observed that the item log does not have comma's so I think there is some problem near the split

**Comment by Pika1998** [comment] 2020-10-04 13:25
The log of the temp variable
```js
[
  '**\n * Represents a book.\n * @constructor\n * @param {string} title ',
  ' The title of the book.\n * @param {string} author ',
  ' The author of the book.\n '
]
```

**Comment by rahil1304** [comment] 2020-10-04 13:27
This is my entire demetifyAPI.js file
```
const vm = require('vm');
function demestifyAPI(api, index, file, routeprefix = '') {
  let METHOD = api.split('.')[1].split('(')[0];
  let trimmedCall = api.match(/\(.[\s\S]*/g)[0];
  trimmedCall = trimmedCall.substring(1, trimmedCall.length - 1);
  let CALL = trimmedCall.split(',')[0];
  CALL = CALL.substring(1, CALL.length - 1);
  let params = getCustomParams(index, file);
  return {
    method: METHOD,
    callName: routeprefix + CALL,
    params,
  };
}

function getCustomParams(index, file) {
  // Backtraces for an immediate multi-line comment
  let descriptionFound = 'unknown';
  let currentIndex = index;
  while (descriptionFound == 'unknown') {
    if (currentIndex != 0) {
      if (
        file.charAt(currentIndex - 1) == ' ' ||
        file.charAt(currentIndex - 1) == '\n' ||
        file.charAt(currentIndex - 1) == '\r'
      ) {
        currentIndex -= 1;
      } else if (file.charAt(currentIndex - 1) == '/') {
        descriptionFound = true;
      } else {
        descriptionFound = false;
      }
    }
  }
  if (descriptionFound) {
    return getCommentedParams(currentIndex, file);
  } else {
    // If no description is present then return null;
    return null;
  }
}

// function getCommentedParams(index, file) {
//   let startIndex = index - 3; //  will be the character before '*' character
//   let currentIndex = startIndex;
//   let params = '';
//   while (file.charAt(currentIndex) != '*') {
//     params = params + file.charAt(currentIndex);
//     currentIndex -= 1;
//   }
//   try {
//     params = JSON.parse([...params].reverse().join('').trim());
//     console.log('Params:', params);
//     return params;
//   } catch (err) {
//     console.log(
//       '\x1b[1m',
//       '\x1b[31m',
//       `❌ Make sure the params passed in comments are in proper JSON Format.`,
//       '\x1b[0m'
//     );
//     return null;
//   }
// }

function getCommentedParams(index, file) {
  let startIndex = index - 3; //  will be the character before '*' character
  let currentIndex = startIndex;
  let params = '';
  let data = {};
  while (file.charAt(currentIndex) != '/') {
    params = params + file.charAt(currentIndex);
    currentIndex -= 1;
  }
  try {
    let item = [...params].reverse().join('').split('\r');
    console.log(item);
    item.forEach(function (param) {
      let temp = param.split('-');
      if (temp.length == 2) {
        temp[0] = temp[0].trim();
        temp[0] = temp[0].substring(temp[0].lastIndexOf(' '));
        data[temp[0].trim()] = String(temp[1].trim());
      }
    });
    console.log(data);
    return data;
  } catch (err) {
    console.log(
      '\x1b[1m',
      '\x1b[31m',
      `❌ Make sure the params passed in comments are in proper JSDoc Format.`,
      '\x1b[0m'
    );
    return null;
  }
}

module.exports = demestifyAPI;

```

**Comment by rahil1304** [comment] 2020-10-04 13:27
Yeah your item should be having commas 

> @rahil1304 my code is not running items.forEach and I observed that the item log does not have comma's so I think there is some problem near the split

**Comment by Pika1998** [comment] 2020-10-04 13:30
@rahil1304 , I replaced the entire file still the same output :cry:

**Comment by Pika1998** [comment] 2020-10-04 13:31
@rahil1304 , I think we should take a break for sometime and call it a day, i will check if there is some issue on my end, will let you know tomorrow :smile: Thank you

**Comment by rahil1304** [comment] 2020-10-04 13:32
So I cloned the repo and ran it again, it's working correctly. Displaying the data properly. 
![image](https://user-images.githubusercontent.com/32304956/95016975-20ba8600-0674-11eb-9911-1f95159c64f2.png)

**Comment by rahil1304** [comment] 2020-10-04 13:34
Which OS are you using? It could be an issue with the `split('/r')` @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 13:34
I am using ubuntu

**Comment by Pika1998** [comment] 2020-10-04 13:35
@rahil1304 Can it be an OS issue?

**Comment by rahil1304** [comment] 2020-10-04 13:36
I'm using windows @Pika1998 
Could you try experimenting with the split function? 
Check this link out. Try changing the` /r` to `/n` and try if it works. 
https://superuser.com/questions/374028/how-are-n-and-r-handled-differently-on-linux-and-windows

**Comment by Pika1998** [comment] 2020-10-04 13:37
@rahil1304  It did work 😂

**Comment by Pika1998** [comment] 2020-10-04 13:38
Now what shall we do keep it `'/r'` or `'/n'`

**Comment by rahil1304** [comment] 2020-10-04 13:39
So I guess it was an OS issue 😂 
I guess keep it `/n` only because it's better if everything works on your pc. 
We'll look into this issue in more detail in the next few days. 
Sounds good? @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 13:40
Sure @rahil1304 
Thanks alot

I guess we learnt a lesson here, we should always write tests before code
and we should run tests for all OS 😂

Don't worry ill push the changes in master :D

**Comment by rahil1304** [comment] 2020-10-04 13:43
I guess you can close this issue since it's resolved now. Let me know if you're thinking of some other features to add to your project. I'm happy to help in any way I can.  @Pika1998

**Comment by Pika1998** [comment] 2020-10-04 13:45
@rahil1304  this solution works for a single key-value pair, but what if we want to do something like this?

> also in json we are giving array for inputs and outputs
> like
> 
> ```js
>  "inputs":{
>         "name":"The username by which he/she logs in",
>         "password": "A string password"
>       },
>       "outputs":{
>         "userid":"The id of the new user created",
>         "error":"Error message if any"
>       }
> ```
> 
> Any idea how we can implement this also ?

**Comment by Pika1998** [comment] 2020-10-04 13:46
@all-contributors please add @rahil1304  for code bug ideas maintenance test

**Comment by rahil1304** [comment] 2020-10-04 13:48
> @rahil1304 this solution works for a single key-value pair, but what if we want to do something like this?
> 
> > also in json we are giving array for inputs and outputs
> > like
> > ```js
> >  "inputs":{
> >         "name":"The username by which he/she logs in",
> >         "password": "A string password"
> >       },
> >       "outputs":{
> >         "userid":"The id of the new user created",
> >         "error":"Error message if any"
> >       }
> > ```
> > 
> > 
> > Any idea how we can implement this also ?

Sure I'll look into this tomorrow. Tired today. Could you make a new issue regarding this? This one has too many comments now 😂

**Comment by Pika1998** [comment] 2020-10-04 13:49
Yes why not, take rest no hurries :smile:

**Closed by Pika1998** 2020-10-04 13:49 UTC
Labels: enhancement, hacktoberfest2020

**Comment by Pika1998** [comment] 2020-10-04 13:58
@rahil1304 checkout Issue #18 and comment there, so I can assign you to it :smile:
